version: '3'
services:
    mysql:
        image: 'mysql:8'
        command: --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '5308:3306'
        environment:
            MYSQL_DATABASE: 'tempdb'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always

    waitmysql:
        image: 'mysql:8'
        links:
            - mysql
        depends_on:
            - mysql
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmysql -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

    postgres:
        image: postgres:15-alpine
        command: '-c full_page_writes=off -c fsync=off -c synchronous_commit=off'
        ports:
            - '25435:5432'
        environment:
            - PGUSER=ludpo
            - PGPASSWORD=lupdos3cRet
            - PGDATABASE=tempdb
            - POSTGRES_USER=lupdo
            - POSTGRES_PASSWORD=lupdos3cRet
            - POSTGRES_DB=tempdb

    waitpostgres:
        image: postgres:15-alpine
        links:
            - postgres
        depends_on:
            - postgres
        entrypoint:
            - bash
            - -c
            - 'until /usr/local/bin/psql postgres://lupdo:lupdos3cRet@postgres/tempdb -c "SELECT 1"; do sleep 5; done'
    
    sqlsrv:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - '21435:1433'
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=lupdo@s3cRet
        healthcheck:
            test: /opt/mssql-tools/bin/sqlcmd -S sqlsrv -U sa -P 'lupdo@s3cRet' -Q 'select 1'

    waitsqlsrv:
        image: mcr.microsoft.com/mssql/server:2022-latest
        links:
            - sqlsrv
        depends_on:
            - sqlsrv
        entrypoint:
            - bash
            - -c
            - 'until /opt/mssql-tools/bin/sqlcmd -S sqlsrv -U sa -P lupdo@s3cRet -d master; do sleep 5; done'

    maria:
        image: 'mariadb:10.11-rc'
        command: --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '31011:3306'
        environment:
            MYSQL_DATABASE: 'tempdb'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always

    waitmaria:
        image: 'mariadb:10.11-rc'
        links:
            - maria
        depends_on:
            - maria
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmaria -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'