version: '3'
services:
    mysql57:
        image: 'mysql:5.7'
        command: --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '5307:3306'
        environment:
            MYSQL_DATABASE: 'tempdb'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always

    waitmysql57:
        image: 'mysql:5.7'
        links:
            - mysql57
        depends_on:
            - mysql57
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmysql57 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

    mysql8:
        image: 'mysql:8'
        command: --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '5308:3306'
        environment:
            MYSQL_DATABASE: 'tempdb'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always

    waitmysql8:
        image: 'mysql:8'
        links:
            - mysql8
        depends_on:
            - mysql8
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmysql8 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

    maria1003:
        image: 'mariadb:10.3'
        command: --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '31003:3306'
        environment:
            MYSQL_DATABASE: 'tempdb'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always

    waitmaria1003:
        image: 'mariadb:10.3'
        links:
            - maria1003
        depends_on:
            - maria1003
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmaria1003 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

    maria1011:
        image: 'mariadb:10.11'
        command: --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '31011:3306'
        environment:
            MYSQL_DATABASE: 'tempdb'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always

    waitmaria1011:
        image: 'mariadb:10.11'
        links:
            - maria1011
        depends_on:
            - maria1011
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmaria1011 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

    postgres11:
        image: postgis/postgis:11-3.3-alpine
        command: '-c full_page_writes=off -c fsync=off -c synchronous_commit=off'
        ports:
            - '25431:5432'
        environment:
            - PGUSER=ludpo
            - PGPASSWORD=lupdos3cRet
            - PGDATABASE=tempdb
            - POSTGRES_USER=lupdo
            - POSTGRES_PASSWORD=lupdos3cRet
            - POSTGRES_DB=tempdb

    waitpostgres11:
        image: postgis/postgis:11-3.3-alpine
        links:
            - postgres11
        depends_on:
            - postgres11
        entrypoint:
            - bash
            - -c
            - 'until /usr/local/bin/psql postgres://lupdo:lupdos3cRet@postgres11/tempdb -c "SELECT 1"; do sleep 5; done'

    postgres15:
        image: postgis/postgis:15-3.3-alpine
        command: '-c full_page_writes=off -c fsync=off -c synchronous_commit=off'
        ports:
            - '25435:5432'
        environment:
            - PGUSER=ludpo
            - PGPASSWORD=lupdos3cRet
            - PGDATABASE=tempdb
            - POSTGRES_USER=lupdo
            - POSTGRES_PASSWORD=lupdos3cRet
            - POSTGRES_DB=tempdb

    waitpostgres15:
        image: postgis/postgis:15-3.3-alpine
        links:
            - postgres15
        depends_on:
            - postgres15
        entrypoint:
            - bash
            - -c
            - 'until /usr/local/bin/psql postgres://lupdo:lupdos3cRet@postgres15/tempdb -c "SELECT 1"; do sleep 5; done'
    
    sqlsrv17:
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
            - '21433:1433'
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=lupdo@s3cRet
        healthcheck:
            test: /opt/mssql-tools/bin/sqlcmd -S sqlsrv17 -U sa -P 'lupdo@s3cRet' -Q 'select 1'

    waitsqlsrv17:
        image: mcr.microsoft.com/mssql/server:2017-latest
        links:
            - sqlsrv17
        depends_on:
            - sqlsrv17
        entrypoint:
            - bash
            - -c
            - 'until /opt/mssql-tools/bin/sqlcmd -S sqlsrv17 -U sa -P lupdo@s3cRet -d master; do sleep 5; done'


    sqlsrv22:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - '21435:1433'
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=lupdo@s3cRet
        healthcheck:
            test: /opt/mssql-tools/bin/sqlcmd -S sqlsrv22 -U sa -P 'lupdo@s3cRet' -Q 'select 1'

    waitsqlsrv22:
        image: mcr.microsoft.com/mssql/server:2022-latest
        links:
            - sqlsrv22
        depends_on:
            - sqlsrv22
        entrypoint:
            - bash
            - -c
            - 'until /opt/mssql-tools/bin/sqlcmd -S sqlsrv22 -U sa -P lupdo@s3cRet -d master; do sleep 5; done'
